# Configurações para o ambiente de setup
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

# Configuração do construtor para usar Nixpacks
[build]
builder = "NIXPACKS"

# Comandos para construir o projeto
[phases.build]
cmds = ['yarn install', 'yarn install postcss postcss-cli', 'yarn build']

# Comando para iniciar o servidor do frontend
[start]
cmd = 'npx serve -s dist -l 5000'

# Configurações de implantação
[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Definindo a porta padrão
port = 5000